Zadatak3
roman
GET http://localhost:9200/knjige/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "opis": "roman"
    }
  }
}

pravda_sudbina
GET http://localhost:9200/knjige/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "opis": "pravda sudbina"
    }
  }
}

Zadatak4
GET /knjige/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "opis": "roman"
          }
        }
      ],
      "filter": [
        {
          "term": {
            "dostupno": true
          }
        },
        {
          "range": {
            "cijena": {
              "lte": 22
            }
          }
        }
      ]
    }
  },
  "sort": [
    {
      "cijena": "asc"
    }
  ]
}

17.
POST http://localhost:9200/knjige/_analyze
Content-Type: application/json

{
  "analyzer": "hrvatski_analyzer",
  "text": "Na Drini ćuprija"
}

21.
GET http://localhost:9200/knjige/_search
Content-Type: application/json

{
  "size": 0,
  "aggs": {
    "po_autoru": {
      "terms": {
        "field": "autor"
      }
    }
  }
}

22.
GET http://localhost:9200/knjige/_search
Content-Type: application/json

{
  "size": 0,
  "aggs": {
    "po_zanru": {
      "terms": {
        "field": "zanr"
      },
      "aggs": {
        "prosjecna_cijena": {
          "avg": {
            "field": "cijena"
          }
        }
      }
    }
  }
}

23.
GET http://localhost:9200/knjige/_search
Content-Type: application/json

{
  "size": 0,
  "aggs": {
    "po_zanru": {
      "terms": {
        "field": "zanr"
      },
      "aggs": {
        "najveca_cijena": {
          "max": {
            "field": "cijena"
          }
        }
      }
    }
  }
}

24.
GET http://localhost:9200/knjige/_search
Content-Type: application/json

{
  "size": 0,
  "aggs": {
    "dostupnost": {
      "terms": {
        "field": "dostupno"
      }
    }
  }
}